version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 12181:2181
      - 18080:8080
    networks:
      local_network:
        ipv4_address: 172.18.0.11
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.2.0'
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      local_network:
        ipv4_address: 172.18.0.12
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ./kafka:/bitnami/kafka

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
